In [1]:
import numpy as np
import pandas as pd

courses=pd.read_csv(r"D:\Coding Language\Python\DataSet\MergingJoining\courses.csv")
students=pd.read_csv(r"D:\Coding Language\Python\DataSet\MergingJoining\students.csv")
nov = pd.read_csv(r"D:\Coding Language\Python\DataSet\MergingJoining\reg-month1.csv")
dec = pd.read_csv(r"D:\Coding Language\Python\DataSet\MergingJoining\reg-month2.csv")
matches=pd.read_csv(r"D:\Coding Language\Python\DataSet\MergingJoining\matches.csv")
delivery=pd.read_csv(r"D:\Coding Language\Python\DataSet\MergingJoining\deliveries (1).csv")

In [ ]:
# pd.concat
pd.concat([nov,dec],ignore_index=True) # If we do not have to restart the concatenate data from index
# 0 then ignore_index=False

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [23]:
# differentiate both data
regs = pd.concat([nov,dec],keys=['Nov','Dec'])
regs.loc['Nov'] # from this code we got november label
# loc is applied on label index and iloc is applied on int idx
# To get the specific row of any label
regs.loc[('Nov',0)]

student_id    23
course_id      1
Name: (Nov, 0), dtype: int64

In [20]:
# to concat across horizontal 
hori = pd.concat([nov,dec],ignore_index=True,axis=1)
hori.shape

(28, 4)

In [25]:
# In join hma doa dataframe koa join krna hota hai on the basis 
# of coumn colum.

# Inner Join:- Joins or gives only common columns
# joa phla ata hai woa left table
students.merge(regs,how='inner',on='student_id')

# In output why student_id is repeated
# The reason student_id appears multiple times is because the regs DataFrame 
# has multiple rows for the same student.

    student_id                name  partner  course_id
0            1       Kailash Harjo       23          1
1            1       Kailash Harjo       23          6
2            1       Kailash Harjo       23         10
3            1       Kailash Harjo       23          9
4            2         Esha Butala        1          5
5            3      Parveen Bhalla        3          3
6            3      Parveen Bhalla        3          5
7            7        Tarun Thaker        9          8
8            7        Tarun Thaker        9         10
9            7        Tarun Thaker        9          7
10           7        Tarun Thaker        9          2
11           7        Tarun Thaker        9          6
12          11  David Mukhopadhyay       20          7
13          11  David Mukhopadhyay       20          8
14          11  David Mukhopadhyay       20         10
15          12          Radha Dutt       19         10
16          12          Radha Dutt       19          1
17          12          Radha Dutt       19          5
18          12          Radha Dutt       19          7
19          13      Munni Varghese       24          3
20          14    Pranab Natarajan       22          9
21          14    Pranab Natarajan       22          6
22          14    Pranab Natarajan       22          4
23          14    Pranab Natarajan       22          1
24          15           Preet Sha       16          5
25          15           Preet Sha       16          1
26          16        Elias Dodiya       25          9
27          16        Elias Dodiya       25          5
28          16        Elias Dodiya       25          7
29          16        Elias Dodiya       25          3
30          17        Yasmin Palan        7          7
31          17        Yasmin Palan        7         10
32          18     Fardeen Mahabir       13          6
33          18     Fardeen Mahabir       13          1
34          18     Fardeen Mahabir       13          8
35          19        Qabeel Raman       12          4
36          19        Qabeel Raman       12          2
37          21          Seema Kota       15          1
38          22          Yash Sethi       21          3
39          22          Yash Sethi       21          5
40          22          Yash Sethi       21          6
41          23      Chhavi Lachman       18          1
42          23      Chhavi Lachman       18          4
43          23      Chhavi Lachman       18          3
44          23      Chhavi Lachman       18          6
45          23      Chhavi Lachman       18          9
46          23      Chhavi Lachman       18          5
47          24        Radhika Suri       17          4
48          25     Shashank D’Alia        2          1
49          25     Shashank D’Alia        2         10

In [27]:
# Left join :- here we get all value of left table and from right table
# we get common between left and right.
courses.merge(regs,how='left',on='course_id')

    course_id       course_name  price  student_id
0           1            python   2499        23.0
1           1            python   2499        18.0
2           1            python   2499         1.0
3           1            python   2499        15.0
4           1            python   2499        21.0
5           1            python   2499        25.0
6           1            python   2499        12.0
7           1            python   2499        14.0
8           1            python   2499        38.0
9           2               sql   3499        19.0
10          2               sql   3499         7.0
11          3     data analysis   4999        22.0
12          3     data analysis   4999        13.0
13          3     data analysis   4999        23.0
14          3     data analysis   4999         3.0
15          3     data analysis   4999        16.0
16          4  machine learning   9999        23.0
17          4  machine learning   9999        19.0
18          4  machine learning   9999        24.0
19          4  machine learning   9999        14.0
20          5           tableau   2499        15.0
21          5           tableau   2499        16.0
22          5           tableau   2499         3.0
23          5           tableau   2499        12.0
24          5           tableau   2499         2.0
25          5           tableau   2499        22.0
26          5           tableau   2499        23.0
27          6          power bi   1899        18.0
28          6          power bi   1899         1.0
29          6          power bi   1899        23.0
30          6          power bi   1899        14.0
31          6          power bi   1899         7.0
32          6          power bi   1899        22.0
33          7          ms sxcel   1599        11.0
34          7          ms sxcel   1599        17.0
35          7          ms sxcel   1599        16.0
36          7          ms sxcel   1599         7.0
37          7          ms sxcel   1599        12.0
38          8            pandas   1099         7.0
39          8            pandas   1099        11.0
40          8            pandas   1099        18.0
41          8            pandas   1099        50.0
42          9            plotly    699        16.0
43          9            plotly    699        14.0
44          9            plotly    699         1.0
45          9            plotly    699        23.0
46          9            plotly    699        42.0
47         10           pyspark   2499         7.0
48         10           pyspark   2499        25.0
49         10           pyspark   2499        12.0
50         10           pyspark   2499        17.0
51         10           pyspark   2499         1.0
52         10           pyspark   2499        11.0
53         11             Numpy    699         NaN
54         12               C++   1299         NaN

In [35]:
# right join :- It given common data and whole right data
temp_df = pd.DataFrame({
    'student_id':[26,27,28],
    'name':['Nitish','Ankit','Rahul'],
    'partner':[28,26,17]
})
students = pd.concat([students,temp_df],ignore_index=True)
print(regs)
students.merge(regs,how='right',on='student_id')

        student_id  course_id
Nov 0           23          1
    1           15          5
    2           18          6
    3           23          4
    4           16          9
    5           18          1
    6            1          1
    7            7          8
    8           22          3
    9           15          1
    10          19          4
    11           1          6
    12           7         10
    13          11          7
    14          13          3
    15          24          4
    16          21          1
    17          16          5
    18          23          3
    19          17          7
    20          23          6
    21          25          1
    22          19          2
    23          25         10
    24           3          3
Dec 0            3          5
    1           16          7
    2           12         10
    3           12          1
    4           14          9
    5            7          7
    6            7          2
    7           16          3
    8           17         10
    9           11          8
    10          14          6
    11          12          5
    12          12          7
    13          18          8
    14           1         10
    15           1          9
    16           2          5
    17           7          6
    18          22          5
    19          22          6
    20          23          9
    21          23          5
    22          14          4
    23          14          1
    24          11         10
    25          42          9
    26          50          8
    27          38          1

    student_id                name  partner  course_id
0           23      Chhavi Lachman     18.0          1
1           15           Preet Sha     16.0          5
2           18     Fardeen Mahabir     13.0          6
3           23      Chhavi Lachman     18.0          4
4           16        Elias Dodiya     25.0          9
5           18     Fardeen Mahabir     13.0          1
6            1       Kailash Harjo     23.0          1
7            7        Tarun Thaker      9.0          8
8           22          Yash Sethi     21.0          3
9           15           Preet Sha     16.0          1
10          19        Qabeel Raman     12.0          4
11           1       Kailash Harjo     23.0          6
12           7        Tarun Thaker      9.0         10
13          11  David Mukhopadhyay     20.0          7
14          13      Munni Varghese     24.0          3
15          24        Radhika Suri     17.0          4
16          21          Seema Kota     15.0          1
17          16        Elias Dodiya     25.0          5
18          23      Chhavi Lachman     18.0          3
19          17        Yasmin Palan      7.0          7
20          23      Chhavi Lachman     18.0          6
21          25     Shashank D’Alia      2.0          1
22          19        Qabeel Raman     12.0          2
23          25     Shashank D’Alia      2.0         10
24           3      Parveen Bhalla      3.0          3
25           3      Parveen Bhalla      3.0          5
26          16        Elias Dodiya     25.0          7
27          12          Radha Dutt     19.0         10
28          12          Radha Dutt     19.0          1
29          14    Pranab Natarajan     22.0          9
30           7        Tarun Thaker      9.0          7
31           7        Tarun Thaker      9.0          2
32          16        Elias Dodiya     25.0          3
33          17        Yasmin Palan      7.0         10
34          11  David Mukhopadhyay     20.0          8
35          14    Pranab Natarajan     22.0          6
36          12          Radha Dutt     19.0          5
37          12          Radha Dutt     19.0          7
38          18     Fardeen Mahabir     13.0          8
39           1       Kailash Harjo     23.0         10
40           1       Kailash Harjo     23.0          9
41           2         Esha Butala      1.0          5
42           7        Tarun Thaker      9.0          6
43          22          Yash Sethi     21.0          5
44          22          Yash Sethi     21.0          6
45          23      Chhavi Lachman     18.0          9
46          23      Chhavi Lachman     18.0          5
47          14    Pranab Natarajan     22.0          4
48          14    Pranab Natarajan     22.0          1
49          11  David Mukhopadhyay     20.0         10
50          42                 NaN      NaN          9
51          50                 NaN      NaN          8
52          38                 NaN      NaN          1

In [56]:
# outer join :- ya dono data ka column provide krta hai..
students.merge(regs,how='outer',on='student_id')

    student_id           name  partner  course_id
0            1  Kailash Harjo     23.0        1.0
1            1  Kailash Harjo     23.0        6.0
2            1  Kailash Harjo     23.0       10.0
3            1  Kailash Harjo     23.0        9.0
4            2    Esha Butala      1.0        5.0
..         ...            ...      ...        ...
67          28          Rahul     17.0        NaN
68          28          Rahul     17.0        NaN
69          38            NaN      NaN        1.0
70          42            NaN      NaN        9.0
71          50            NaN      NaN        8.0

[72 rows x 4 columns]

In [58]:
# Find total revenue generated
total = regs.merge(courses,how='left',on='course_id')['price'].sum()
int(total)

154247

In [ ]:
# Find month by month revenue