In [3]:
import numpy as np 
import pandas as pd
df = pd.read_csv(r"D:\Coding Language\Python\DataSet\PandasTextualData\IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
"""
# a) Data gathering

# b) Cleaning

# c) Preprocessing :-
# 1. Tokenization -> I am Nitish = [I,am,Nitish]
# 2. Stopword removal -> stopword = and,I,have,could. 
# Stopword are the words which do not help in meaning
# Only help in sentance formation.
# 3. Steaming :- apna word koa root form mai la ata hoa.
 # e.g. dance,danced,dancing =>dance

# Now data is in goog format.
 
# d) EDA(Exploratory Data Analysis)
# e) make features
# f) vectorization :- text koa number mai convert krna wala process koa vectorization bolta hai.
# ml models works only on number.

# After that Data scientist work start. Previously Data analyst will do.
# g) modeling
# h) evaluation
# i) Deploy
# j) Monitor

"""

'\n# a) Data gathering\n\n# b) Cleaning\n\n# c) Preprocessing :-\n# 1. Tokenization -> I am Nitish = [I,am,Nitish]\n# 2. Stopword removal -> stopword = and,I,have,could. \n# Stopword are the words which do not help in meaning\n# Only help in sentance formation.\n# 3. Steaming :- apna word koa root form mai la ata hoa.\n # e.g. dance,danced,dancing =>dance\n\n# Now data is in goog format.\n\n# d) EDA(Exploratory Data Analysis)\n# e) make features\n# f) vectorization :- text koa number mai convert krna wala process koa vectorization bolta hai.\n# ml models works only on number.\n\n# After that Data scientist work start. Previously Data analyst will do.\n# g) modeling\n# h) evaluation\n# i) Deploy\n# j) Monitor\n\n'

In [8]:
df.info() # There is not any null values.
df.duplicated().sum() # There are duplicate values that we have to remove.
df=df.drop_duplicates()

<class 'pandas.core.frame.DataFrame'>
Index: 49582 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     49582 non-null  object
 1   sentiment  49582 non-null  object
dtypes: object(2)
memory usage: 1.1+ MB

In [9]:
# Cleaning

# 1. convert into lower case
df['review']=df['review'].str.lower()
df['review']=df['review'].str.strip()
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [10]:
import re

# def  remove_html(data):
#     data=re.sub(r'<.*?>','',data)
#     return data

# remove_html('<p>my name is nitish</p><br><img>')


# remove html tags
df['review']=df['review'].str.replace(r'<.*?>','',regex=True)

# code to check if a review contains an URL
df[df['review'].str.contains(r"https?://\S+|www\.\S+",regex=True,na=False)].iloc[4].values

# code to remove a URL
df['review'] = df['review'].str.replace(r"https?://\S+|www\.\S+",'',regex=True)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [13]:
# expanding abbvr

# expand 

def remove_abb(data):
    if pd.isna(data):   # Handles None and NaN
        return data
    data = re.sub(r"he's","he is", data)
    data = re.sub(r"there's", "there is", data)
    data = re.sub(r"We're", "We are", data)
    data = re.sub(r"That's", "That is", data)
    data = re.sub(r"won't", "will not", data)
    data = re.sub(r"they're", "they are", data)
    data = re.sub(r"Can't", "Cannot", data)
    data = re.sub(r"wasn't", "was not", data)
    data = re.sub(r"don\x89Ûªt", "do not", data)
    data= re.sub(r"aren't", "are not", data)
    data = re.sub(r"isn't", "is not", data)
    data = re.sub(r"What's", "What is", data)
    data = re.sub(r"haven't", "have not", data)
    data = re.sub(r"hasn't", "has not", data)
    data = re.sub(r"There's", "There is", data)
    data = re.sub(r"He's", "He is", data)
    data = re.sub(r"It's", "It is", data)
    data = re.sub(r"You're", "You are", data)
    data = re.sub(r"I'M", "I am", data)
    data = re.sub(r"shouldn't", "should not", data)
    data = re.sub(r"wouldn't", "would not", data)
    data = re.sub(r"i'm", "I am", data)
    data = re.sub(r"I\x89Ûªm", "I am", data)
    data = re.sub(r"I'm", "I am", data)
    data = re.sub(r"Isn't", "is not", data)
    data = re.sub(r"Here's", "Here is", data)
    data = re.sub(r"you've", "you have", data)
    data = re.sub(r"you\x89Ûªve", "you have", data)
    data = re.sub(r"we're", "we are", data)
    data = re.sub(r"what's", "what is", data)
    data = re.sub(r"couldn't", "could not", data)
    data = re.sub(r"we've", "we have", data)
    data = re.sub(r"it\x89Ûªs", "it is", data)
    data = re.sub(r"doesn\x89Ûªt", "does not", data)
    data = re.sub(r"It\x89Ûªs", "It is", data)
    data = re.sub(r"Here\x89Ûªs", "Here is", data)
    data = re.sub(r"who's", "who is", data)
    data = re.sub(r"I\x89Ûªve", "I have", data)
    data = re.sub(r"y'all", "you all", data)
    data = re.sub(r"can\x89Ûªt", "cannot", data)
    data = re.sub(r"would've", "would have", data)
    data = re.sub(r"it'll", "it will", data)
    data = re.sub(r"we'll", "we will", data)
    data = re.sub(r"wouldn\x89Ûªt", "would not", data)
    data = re.sub(r"We've", "We have", data)
    data = re.sub(r"he'll", "he will", data)
    data = re.sub(r"Y'all", "You all", data)
    data = re.sub(r"Weren't", "Were not", data)
    data = re.sub(r"Didn't", "Did not", data)
    data = re.sub(r"they'll", "they will", data)
    data = re.sub(r"they'd", "they would", data)
    data = re.sub(r"DON'T", "DO NOT", data)
    data = re.sub(r"That\x89Ûªs", "That is", data)
    data = re.sub(r"they've", "they have", data)
    data = re.sub(r"i'd", "I would", data)
    data = re.sub(r"should've", "should have", data)
    data = re.sub(r"You\x89Ûªre", "You are", data)
    data = re.sub(r"where's", "where is", data)
    data = re.sub(r"Don\x89Ûªt", "Do not", data)
    data = re.sub(r"we'd", "we would", data)
    data = re.sub(r"i'll", "I will", data)
    data = re.sub(r"weren't", "were not", data)
    data = re.sub(r"They're", "They are", data)
    data = re.sub(r"Can\x89Ûªt", "Cannot", data)
    data = re.sub(r"you\x89Ûªll", "you will", data)
    data = re.sub(r"I\x89Ûªd", "I would", data)
    data = re.sub(r"let's", "let us", data)
    data = re.sub(r"it's", "it is", data)
    data = re.sub(r"can't", "cannot", data)
    data = re.sub(r"don't", "do not", data)
    data = re.sub(r"you're", "you are", data)
    data = re.sub(r"i've", "I have", data)
    data = re.sub(r"that's", "that is", data)
    data = re.sub(r"i'll", "I will", data)
    data = re.sub(r"doesn't", "does not",data)
    data = re.sub(r"i'd", "I would", data)
    data = re.sub(r"didn't", "did not", data)
    data = re.sub(r"ain't", "am not", data)
    data = re.sub(r"you'll", "you will", data)
    data = re.sub(r"I've", "I have", data)
    data = re.sub(r"Don't", "do not", data)
    data = re.sub(r"I'll", "I will", data)
    data = re.sub(r"I'd", "I would", data)
    data = re.sub(r"Let's", "Let us", data)
    data = re.sub(r"you'd", "You would", data)
    data = re.sub(r"It's", "It is", data)
    data = re.sub(r"Ain't", "am not", data)
    data = re.sub(r"Haven't", "Have not", data)
    data = re.sub(r"Could've", "Could have", data)
    data = re.sub(r"youve", "you have", data)  
    data = re.sub(r"donå«t", "do not", data)
    
    return data

In [15]:
df['review'] = df['review'].apply(remove_abb)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there is a family where a little boy...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  I am going to have to disagree with the previo...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [ ]:
# This module can correct the spelling 
from textblob import TextBlob

text = "hi I can drve at nigt"
result = TextBlob(text).correct().string
print(result)

def spelling_correction(text):
    if pd.isna(text):
        return text
    return TextBlob(text).correct().string

df['review'].apply(spelling_correction)


# Puctuations :- Aisa symbol jska koi meaning hota hai e.g ?,! etc
# Remove Punctations

import string
string.punctuation

hi I can drove at night

In [ ]:
def remove_puctuation(text):
    
    for i in string.punctuation:
        if i in text:
            text = text.replace(i,'')
            
    return text

In [ ]:
df['review'] = df['review'].apply(remove_puctuation)
df['review'].head()

In [ ]:
# Stop word removal
from nltk.corpus import stopwords

def remove_stopwords(text):
    L=[]
    for word in text:
        if word not in stopwords.words('english'):
            L.append(word)

    return L

In [ ]:
df['tokenized_review']=df['tokenized_review'].apply(remove_stopwords)
df['tokenized_review']=df['tokenized_review'].apply(lambda x:" ".join(x))

In [ ]:
# EDA

df['char_length'] = df['review'].str.len()
df['word_length'] = df['tokenized_review'].apply(len)

In [ ]:
import seaborn as sns
sns.distplot(df[df['sentiment'] == 'positive']['char_length'])
sns.distplot(df[df['sentiment'] == 'negative']['char_length'])


# But this features(char_length and word_length) do not distinguish between positive and negative review.
# As you see the graph.

In [ ]:
sns.distplot(df[df['sentiment'] == 'positive']['word_length'])
sns.distplot(df[df['sentiment'] == 'negative']['word_length'])

In [ ]:
# Unigrams - contains one word
# I am Nitish My weight is 70
# Unigram-> I,am,Nitish,My,weight,is,70

# Bigrams :- contains pair of two words.
# e.g. -> [I,am],[am,Nitish],[Nitish,my]...

# trigrams :- contaons pair of three words.

from nltk import ngrams

pd.Series(ngrams(df['tokenized_review'].sum(),2)).value_counts()  # Bigrams code

pd.Series(ngrams(df['tokenized_review'].sum(),3)).value_counts()  # trigrams code

# if we find bigrams for positive and negative review both are different

In [ ]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt

plt.figure(figsize = (20,20)) # Positive Review Text
wc = WordCloud(width = 1600 , height = 800).generate(" ".join(df[df['sentiment'] == 'positive']['review']))
plt.imshow(wc)

In [ ]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt

plt.figure(figsize = (20,20)) # Positive Review Text
wc = WordCloud(width = 1600 , height = 800).generate(" ".join(df[df['sentiment'] == 'negative']['review']))
plt.imshow(wc)